### ISSUE TITLE
这是全量评测集合吗？

### ISSUE THREAD

**Issue by moka11moka** [open-compass/CompassBench#3]
Hi, 你好

这个工作非常棒，很感谢开源。但我有一个问题，

我看中文的评测集合只有不到20条，这是全量的数据吗？

如果不是的话，哪里可以看到全量评测集合呢？

Best Regards.

**Comment by tonysy** [comment]
We provide the demo data for OpenCompass leaderboard. The full set is close-source to avoid data contaimination.
