### ISSUE TITLE
compassbench math评测集疑问

### ISSUE THREAD

**Issue by sxqqslf** [open-compass/CompassBench#4]
你好，公开的math数据 id = [73, 91, 92, 98] 这四个题目的选项似乎是一样的，并且id=98这题考察了图像，麻烦确认下题目是否有问题

{"id": "73", "question": "集合$A=\\{1,2,3,4,5,9\\}$，$B = \\left\\{ x | \\sqrt { x } \\in A \\right\\}$，则$\\complement_{A}(A\\cap B)=$（ ）．", "explanation": "因为$$A=\\{1,2,3,4,5,9\\}$$，$$B = \\left\\{ x | \\sqrt { x } \\in A \\right\\}=\\{1,4,9,16,25,81\\}$$， 所以$$\\complement_{A}(A\\cap B)=\\{2,3,5\\}$$， 故选：$$\\text{D}$$．", "options": ["$\\{2,3,5\\}$", "$\\{2,3,5\\}$", "$\\{2,3,5\\}$", "$\\{2,3,5\\}$"], "answer": "D"}

{"id": "91", "question": "集合$A=\\{1,2,3,4,5,9\\}$，$B=\\{x|x+1\\in A\\}$，则$A\\cap B=$（ ）．", "explanation": "因为$$A=\\{1,2,3,4,5,9\\}$$，$$B=\\{x|x+1\\in A\\}=\\{0,1,2,3,4,8\\}$$， >所以$$A\\cap B=\\{1,2,3,4\\}$$． 故选$$ \\rm A$$．", "options": ["$\\{1,2,3,4\\}$", "$\\{1,2,3,4\\}$", "$ \\{1,2,3,4\\}$", "$ \\{1,2,3,4\\}$"], "answer": "A"}

{"id": "98", "question": "函数$f(x)=-x^2+(\\text{e} ^x-\\text{e}^{-x})\\sin x$的大致图像为（ ）．", "explanation": "选$$B$$．", "options": ["$1$", "$1$", "$1$", "$1$"], "answer": "B"}

{"id": "92", "question": "设$z=\\sqrt{2}\\text{i} $，则$z\\cdot \\overline z=$（ ）．", "explanation": "因为$$ z = \\sqrt { 2 }\\text{i} $$， 所以$$z\\cdot \\overline z=2$$． 故选$$D$$．", "options": ["$2$", "$2$", "$2$", "$2$"], "answer": "D"}

**Comment by tonysy** [comment]
Thanks for the report, we will check the data and remove the invalid data.

**Comment by tonysy** [comment]
We have fix the error in math data, these errors are introduced in the original data : https://www.gaokzx.com/gk/shitiku/123353.html.

Thanks again.
